[package]
authors = ["Jaroslaw Weber <jaroslaw.weber@gmail.com>"]
name = "relm-calculator"
version = "0.1.0"

[dependencies]
gtk = "0.1.3"
meval = "0.0.9"
relm = "0.9.6"
relm-attributes = "0.9.0"
relm-derive = "0.9.2"